---
title: "Midterm Project Part 3"
subtitle: "Visualization of Bite Rates"
author: "Madeline Greene"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [metropolis,robot, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scracth can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = FALSE, fig.retina = 3)
library(flipbookr)
library(tidyverse)
```


```{r data-wrangling}
## read in the data
read_csv("plot_bites.csv") -> data_plot_bites

head(data_plot_bites)

## get it in plotable form
data_plot_bites %>%
  filter(treatment %in% c("Control", "External")) %>%
  #only need these two treatments
  mutate(time_corr_bites_hour = (timeCorrBites/60))%>%
  #need it out of an hour not minutes
  select(treatment,family, Month, Year, time_corr_bites_hour) -> plot_bites_flipbook

head(plot_bites_flipbook)

```

```{r myplot, include=F}
  ggplot(plot_bites_flipbook, aes(x = Month, y= time_corr_bites_hour)) +
  #viewing change of bites per month
  labs(y = "Bites Per Hour") +
  #changed y-axis title
  labs(color = "Treatment") +
  #changed legend title
  theme(strip.background = element_rect(fill = "seashell2")) +
  scale_color_brewer(palette= "Dark2") +
  #colorblind friendly palette
  geom_point(aes(color= treatment),position = position_dodge2(width = 0.6), size = 1) +
  #geom_point creates a scatterplot in which I colored by treatment
  facet_wrap(~Year)+
  #split up by Year
  facet_wrap(family~Year)
  #split up compare by Year and family of species
  
  
  

```
---

`r chunk_reveal("myplot")`

---

